# Generated by Django 5.0.6 on 2026-06-23 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อหมวดหมู่')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียด')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
            ],
            options={
                'verbose_name': 'หมวดหมู่สินค้า',
                'verbose_name_plural': 'หมวดหมู่สินค้า',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='เลขที่ใบเสร็จ')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ยอดรวมก่อนภาษี')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ภาษีมูลค่าเพิ่ม (VAT)')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ยอดสุทธิ')),
                ('payment_method', models.CharField(choices=[('CASH', 'เงินสด'), ('CREDIT_CARD', 'บัตรเครดิต'), ('PROMPTPAY', 'พร้อมเพย์ / โอนเงิน'), ('OTHER', 'อื่นๆ')], default='CASH', max_length=20, verbose_name='วิธีชำระเงิน')),
                ('status', models.CharField(choices=[('PENDING', 'รอชำระเงิน'), ('COMPLETED', 'ชำระเงินแล้ว'), ('CANCELLED', 'ยกเลิก')], default='COMPLETED', max_length=20, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่ทำรายการ')),
                ('cashier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='พนักงานขาย')),
            ],
            options={
                'verbose_name': 'ใบเสร็จรับเงิน / ออเดอร์',
                'verbose_name_plural': 'ใบเสร็จรับเงิน / ออเดอร์',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อสินค้า')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='รหัสสินค้า (SKU)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคา')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='จำนวนคงเหลือ')),
                ('is_active', models.BooleanField(default=True, verbose_name='พร้อมขาย')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขล่าสุด')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='marketing.category', verbose_name='หมวดหมู่')),
            ],
            options={
                'verbose_name': 'สินค้า',
                'verbose_name_plural': 'สินค้า',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='จำนวน')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคาต่อหน่วย')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคารวม')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='marketing.order', verbose_name='ออเดอร์')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marketing.product', verbose_name='สินค้า')),
            ],
            options={
                'verbose_name': 'รายการสินค้าในบิล',
                'verbose_name_plural': 'รายการสินค้าในบิล',
            },
        ),
    ]
