# Generated by Django 6.0.6 on 2026-06-16 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อหมวดหมู่')),
                ('icon', models.CharField(default='📦', max_length=50, verbose_name='ไอคอน')),
            ],
            options={
                'verbose_name': 'หมวดหมู่',
                'verbose_name_plural': 'หมวดหมู่ทั้งหมด',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อสินค้า')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียดสินค้า')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคา')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='ลิงก์รูปภาพ')),
                ('stock', models.IntegerField(default=0, verbose_name='จำนวนคงเหลือ')),
                ('sold', models.IntegerField(default=0, verbose_name='ขายแล้ว')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='storefront.category', verbose_name='หมวดหมู่')),
            ],
            options={
                'verbose_name': 'สินค้า',
                'verbose_name_plural': 'สินค้าทั้งหมด',
            },
        ),
    ]
